on: push
name: New workflow
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: markdown-link-check
      uses: ./
      with:
        use-quiet-mode: 'yes'
        folder-path: 'md'
    - name: shellcheck
      uses: ludeeus/action-shellcheck@0.1.0

