on: [pull_request]
name: PR Checks
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: markdown-link-check
      uses: ./
      with:
        use-quiet-mode: 'yes'
        folder-path: 'md/dir1, md/dir2'
        file-path: './README.md, ./LICENSE, ./md/file4.markdown'
  shellcheck:
    runs-on: [ubuntu-latest]
    steps:
      - uses: 'bewuethr/shellcheck-action@v2'
