on: [pull_request]
name: PR Checks
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: markdown-link-check
      uses: ./
      with:
        check-modified-files-only: 'yes'
  markdown-link-check-folders:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: markdown-link-check
      uses: ./
      with:
        # Add a test to restrict the test to just dir4 and dir5.
        folder-path: './md/dir4, ./md/dir5'
  shellcheck:
    runs-on: [ubuntu-latest]
    steps:
      - uses: 'bewuethr/shellcheck-action@v2'
