on: [pull_request]
name: PR Checks
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: markdown-link-check
      uses: ./
      with:
        use-quiet-mode: 'yes'
        folder-path: 'md'
        check-modified-files-only: 'yes'
  shellcheck:
    runs-on: [ubuntu-latest]
    steps:
      - uses: 'bewuethr/shellcheck-action@v2'
